// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice =
  BlogImageSlice | BlogCtaSlice | BlogTextSlice | BlogHeroSlice;

/**
 * Content for blog post documents
 */
interface BlogPostDocumentData {
  /**
   * Listing Title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.listing_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  listing_title: prismic.KeyTextField;

  /**
   * Listing Excerpt field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.listing_excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  listing_excerpt: prismic.KeyTextField;

  /**
   * Thumbnail field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Category field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Reading Time field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.reading_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reading_time: prismic.KeyTextField;

  /**
   * Author Name field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Featured field in *blog post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Display Order field in *blog post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.display_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Slice Zone field in *blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>; /**
   * Meta Title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *project → project_metrics*
 */
export interface ProjectDocumentDataProjectMetricsItem {}

type ProjectDocumentDataSlicesSlice =
  | StatisticsSlice
  | SolutionSlice
  | ScreenshotGallerySlice
  | FeatureListSlice
  | RichTextSlice
  | FaqsSlice
  | ArchitectureSlice
  | DevelopmentProcessSlice
  | CtaSlice
  | ChallengeSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * project_name field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_name: prismic.KeyTextField;

  /**
   * project_description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_description: prismic.KeyTextField;

  /**
   * featured field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * dispaly_order field in *project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project.dispaly_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  dispaly_order: prismic.NumberField;

  /**
   * status field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  status: prismic.KeyTextField;

  /**
   * client_type field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.client_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_type: prismic.KeyTextField;

  /**
   * industry field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.industry
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  industry: prismic.KeyTextField;

  /**
   * role field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * duration field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.duration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration: prismic.KeyTextField;

  /**
   * team_size field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.team_size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  team_size: prismic.KeyTextField;

  /**
   * live_url field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.live_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * github_link field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.github_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * demo_video field in *project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project.demo_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  demo_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * project_metrics field in *project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_metrics[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_metrics: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectMetricsItem>
  >;

  /**
   * card_thumnail field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.card_thumnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_thumnail: prismic.ImageField<never>;

  /**
   * hero_banner field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.hero_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_banner: prismic.ImageField<never>;

  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>; /**
   * Meta Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *service → Technologies*
 */
export interface ServiceDocumentDataTechnologiesItem {
  /**
   * technology field in *service → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.technologies[].technology
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technology: prismic.KeyTextField;
}

/**
 * Item in *service → Deliverables*
 */
export interface ServiceDocumentDataDeliverablesItem {
  /**
   * title field in *service → Deliverables*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.deliverables[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *service → Deliverables*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.deliverables[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *service → Pricing plans*
 */
export interface ServiceDocumentDataPricingPlansItem {
  /**
   * plan_description field in *service → Pricing plans*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].plan_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  plan_description: prismic.RichTextField;

  /**
   * plan_name field in *service → Pricing plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].plan_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plan_name: prismic.KeyTextField;

  /**
   * timeline field in *service → Pricing plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].timeline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  timeline: prismic.KeyTextField;

  /**
   * features field in *service → Pricing plans*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField;

  /**
   * button field in *service → Pricing plans*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * featured field in *service → Pricing plans*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service.pricing_plans[].featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * price field in *service → Pricing plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;
}

/**
 * Item in *service → CTA*
 */
export interface ServiceDocumentDataCtaItem {
  /**
   * cta_heading field in *service → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.cta[].cta_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_heading: prismic.KeyTextField;

  /**
   * cta_description field in *service → CTA*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.cta[].cta_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField;

  /**
   * cta_button field in *service → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.cta[].cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

type ServiceDocumentDataSlicesSlice = never;

/**
 * Content for service documents
 */
interface ServiceDocumentData {
  /**
   * Service name field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_name: prismic.KeyTextField;

  /**
   * Short description field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * Card image field in *service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.card_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Hero image field in *service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Featured field in *service*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Display order field in *service*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: service.display_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Status field in *service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  status: prismic.SelectField<"Available" | "2">;

  /**
   * Typical timeline field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.typical_timeline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  typical_timeline: prismic.KeyTextField;

  /**
   * Delivery model field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.delivery_model
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  delivery_model: prismic.KeyTextField;

  /**
   * Starting price field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.starting_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  starting_price: prismic.KeyTextField;

  /**
   * Primary CTA field in *service*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Technologies field in *service*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<ServiceDocumentDataTechnologiesItem>
  >;

  /**
   * Deliverables field in *service*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service.deliverables[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  deliverables: prismic.GroupField<
    Simplify<ServiceDocumentDataDeliverablesItem>
  >;

  /**
   * Pricing plans field in *service*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service.pricing_plans[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pricing_plans: prismic.GroupField<
    Simplify<ServiceDocumentDataPricingPlansItem>
  >;

  /**
   * Overview heading field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.overview_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overview_heading: prismic.KeyTextField;

  /**
   * Overview content field in *service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.overview_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  overview_content: prismic.RichTextField;

  /**
   * CTA field in *service*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<ServiceDocumentDataCtaItem>>;

  /**
   * Slice Zone field in *service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice>; /**
   * Meta Title field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  BlogPostDocument | ProjectDocument | ServiceDocument;

/**
 * Primary content in *Architecture → Default → Primary*
 */
export interface ArchitectureSliceDefaultPrimary {
  /**
   * heading field in *Architecture → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architecture.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *Architecture → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architecture.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Architecture Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchitectureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArchitectureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Architecture*
 */
type ArchitectureSliceVariation = ArchitectureSliceDefault;

/**
 * Architecture Shared Slice
 *
 * - **API ID**: `architecture`
 * - **Description**: Architecture
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchitectureSlice = prismic.SharedSlice<
  "architecture",
  ArchitectureSliceVariation
>;

/**
 * Primary content in *BlogCta → Default → Primary*
 */
export interface BlogCtaSliceDefaultPrimary {
  /**
   * heading field in *BlogCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *BlogCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *BlogCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cta.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * button field in *BlogCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_cta.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for BlogCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogCta*
 */
type BlogCtaSliceVariation = BlogCtaSliceDefault;

/**
 * BlogCta Shared Slice
 *
 * - **API ID**: `blog_cta`
 * - **Description**: BlogCta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogCtaSlice = prismic.SharedSlice<
  "blog_cta",
  BlogCtaSliceVariation
>;

/**
 * Primary content in *BlogHero → Default → Primary*
 */
export interface BlogHeroSliceDefaultPrimary {
  /**
   * heading field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * hero_image field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * background_image field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * use_background field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_hero.default.primary.use_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_background: prismic.BooleanField;
}

/**
 * Default variation for BlogHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogHero*
 */
type BlogHeroSliceVariation = BlogHeroSliceDefault;

/**
 * BlogHero Shared Slice
 *
 * - **API ID**: `blog_hero`
 * - **Description**: BlogHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHeroSlice = prismic.SharedSlice<
  "blog_hero",
  BlogHeroSliceVariation
>;

/**
 * Primary content in *BlogImage → Default → Primary*
 */
export interface BlogImageSliceDefaultPrimary {
  /**
   * image field in *BlogImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogImage*
 */
type BlogImageSliceVariation = BlogImageSliceDefault;

/**
 * BlogImage Shared Slice
 *
 * - **API ID**: `blog_image`
 * - **Description**: BlogImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogImageSlice = prismic.SharedSlice<
  "blog_image",
  BlogImageSliceVariation
>;

/**
 * Primary content in *BlogText → Default → Primary*
 */
export interface BlogTextSliceDefaultPrimary {
  /**
   * content field in *BlogText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for BlogText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogText*
 */
type BlogTextSliceVariation = BlogTextSliceDefault;

/**
 * BlogText Shared Slice
 *
 * - **API ID**: `blog_text`
 * - **Description**: BlogText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogTextSlice = prismic.SharedSlice<
  "blog_text",
  BlogTextSliceVariation
>;

/**
 * Primary content in *Challenge → Default → Primary*
 */
export interface ChallengeSliceDefaultPrimary {
  /**
   * heading field in *Challenge → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: challenge.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *Challenge → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: challenge.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Challenge Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChallengeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChallengeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Challenge*
 */
type ChallengeSliceVariation = ChallengeSliceDefault;

/**
 * Challenge Shared Slice
 *
 * - **API ID**: `challenge`
 * - **Description**: Challenge
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChallengeSlice = prismic.SharedSlice<
  "challenge",
  ChallengeSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * heading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * desc field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.desc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  desc: prismic.RichTextField;

  /**
   * btn field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *DevelopmentProcess → Default → Primary*
 */
export interface DevelopmentProcessSliceDefaultPrimary {
  /**
   * heading field in *DevelopmentProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development_process.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *DevelopmentProcess → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development_process.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for DevelopmentProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DevelopmentProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DevelopmentProcessSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DevelopmentProcess*
 */
type DevelopmentProcessSliceVariation = DevelopmentProcessSliceDefault;

/**
 * DevelopmentProcess Shared Slice
 *
 * - **API ID**: `development_process`
 * - **Description**: DevelopmentProcess
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DevelopmentProcessSlice = prismic.SharedSlice<
  "development_process",
  DevelopmentProcessSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → faqs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * question field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * faqs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Item in *FeatureList → Default → Primary → Repeater*
 */
export interface FeatureListSliceDefaultPrimaryRepeaterItem {
  /**
   * title field in *FeatureList → Default → Primary → Repeater*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.repeater[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * desc field in *FeatureList → Default → Primary → Repeater*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.repeater[].desc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  desc: prismic.RichTextField;
}

/**
 * Primary content in *FeatureList → Default → Primary*
 */
export interface FeatureListSliceDefaultPrimary {
  /**
   * heading field in *FeatureList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Repeater field in *FeatureList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.repeater[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeater: prismic.GroupField<
    Simplify<FeatureListSliceDefaultPrimaryRepeaterItem>
  >;
}

/**
 * Default variation for FeatureList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureList*
 */
type FeatureListSliceVariation = FeatureListSliceDefault;

/**
 * FeatureList Shared Slice
 *
 * - **API ID**: `feature_list`
 * - **Description**: FeatureList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureListSlice = prismic.SharedSlice<
  "feature_list",
  FeatureListSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * heading field in *RichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *ScreenshotGallery → Default → Primary → images*
 */
export interface ScreenshotGallerySliceDefaultPrimaryImagesItem {
  /**
   * image field in *ScreenshotGallery → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screenshot_gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ScreenshotGallery → Default → Primary*
 */
export interface ScreenshotGallerySliceDefaultPrimary {
  /**
   * images field in *ScreenshotGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: screenshot_gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<ScreenshotGallerySliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for ScreenshotGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenshotGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenshotGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScreenshotGallery*
 */
type ScreenshotGallerySliceVariation = ScreenshotGallerySliceDefault;

/**
 * ScreenshotGallery Shared Slice
 *
 * - **API ID**: `screenshot_gallery`
 * - **Description**: ScreenshotGallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenshotGallerySlice = prismic.SharedSlice<
  "screenshot_gallery",
  ScreenshotGallerySliceVariation
>;

/**
 * Primary content in *Solution → Default → Primary*
 */
export interface SolutionSliceDefaultPrimary {
  /**
   * heading field in *Solution → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *Solution → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Solution Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Solution*
 */
type SolutionSliceVariation = SolutionSliceDefault;

/**
 * Solution Shared Slice
 *
 * - **API ID**: `solution`
 * - **Description**: Solution
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionSlice = prismic.SharedSlice<
  "solution",
  SolutionSliceVariation
>;

/**
 * Item in *Statistics → Default → Primary → Statistics*
 */
export interface StatisticsSliceDefaultPrimaryStatisticsItem {
  /**
   * score field in *Statistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[].score
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  score: prismic.KeyTextField;

  /**
   * desc field in *Statistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[].desc
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  desc: prismic.KeyTextField;
}

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
  /**
   * Statistics field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  statistics: prismic.GroupField<
    Simplify<StatisticsSliceDefaultPrimaryStatisticsItem>
  >;
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatisticsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault;

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatisticsSlice = prismic.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataProjectMetricsItem,
      ProjectDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataTechnologiesItem,
      ServiceDocumentDataDeliverablesItem,
      ServiceDocumentDataPricingPlansItem,
      ServiceDocumentDataCtaItem,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      ArchitectureSlice,
      ArchitectureSliceDefaultPrimary,
      ArchitectureSliceVariation,
      ArchitectureSliceDefault,
      BlogCtaSlice,
      BlogCtaSliceDefaultPrimary,
      BlogCtaSliceVariation,
      BlogCtaSliceDefault,
      BlogHeroSlice,
      BlogHeroSliceDefaultPrimary,
      BlogHeroSliceVariation,
      BlogHeroSliceDefault,
      BlogImageSlice,
      BlogImageSliceDefaultPrimary,
      BlogImageSliceVariation,
      BlogImageSliceDefault,
      BlogTextSlice,
      BlogTextSliceDefaultPrimary,
      BlogTextSliceVariation,
      BlogTextSliceDefault,
      ChallengeSlice,
      ChallengeSliceDefaultPrimary,
      ChallengeSliceVariation,
      ChallengeSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      DevelopmentProcessSlice,
      DevelopmentProcessSliceDefaultPrimary,
      DevelopmentProcessSliceVariation,
      DevelopmentProcessSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FeatureListSlice,
      FeatureListSliceDefaultPrimaryRepeaterItem,
      FeatureListSliceDefaultPrimary,
      FeatureListSliceVariation,
      FeatureListSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScreenshotGallerySlice,
      ScreenshotGallerySliceDefaultPrimaryImagesItem,
      ScreenshotGallerySliceDefaultPrimary,
      ScreenshotGallerySliceVariation,
      ScreenshotGallerySliceDefault,
      SolutionSlice,
      SolutionSliceDefaultPrimary,
      SolutionSliceVariation,
      SolutionSliceDefault,
      StatisticsSlice,
      StatisticsSliceDefaultPrimaryStatisticsItem,
      StatisticsSliceDefaultPrimary,
      StatisticsSliceVariation,
      StatisticsSliceDefault,
    };
  }
}
