// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  architecture: dynamic(() => import("./Architecture")),
  blog_cta: dynamic(() => import("./BlogCta")),
  blog_hero: dynamic(() => import("./BlogHero")),
  blog_image: dynamic(() => import("./BlogImage")),
  blog_text: dynamic(() => import("./BlogText")),
  challenge: dynamic(() => import("./Challenge")),
  cta: dynamic(() => import("./Cta")),
  development_process: dynamic(() => import("./DevelopmentProcess")),
  faqs: dynamic(() => import("./Faqs")),
  feature_list: dynamic(() => import("./FeatureList")),
  rich_text: dynamic(() => import("./RichText")),
  screenshot_gallery: dynamic(() => import("./ScreenshotGallery")),
  solution: dynamic(() => import("./Solution")),
  statistics: dynamic(() => import("./Statistics")),
};
